GET http://localhost:3000/songs

###

GET http://localhost:3000/songs/1

###

POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Lingus",
  "artist": "Snarky Puppy",
  "album": "Vol. 3",
  "year": 2009
}

###

PATCH http://localhost:3000/songs/5
Content-Type: application/json

{
  "title": "Yellow",
  "artist": "Snow",
  "album": "LECHUGA",
  "year": 2022
}

###

DELETE http://localhost:3000/songs/5
Content-Type: application/json